version: '3'

services:
  ssb-deno:
    image: reto/ssb-deno
    build: .
    ports:
      - "8008:8008"
      - "127.0.0.1:8990:8990"
    volumes:
      - /var/ssb-deno:/root/.ssb
    restart: unless-stopped
