version: '3'
services:
  tricerascuttler:
    image: reto/tricerascuttler
    build: 
      context: ..
      dockerfile: tricerascuttler/Dockerfile
    ports:
      - "8008:8008"
      - "127.0.0.1:8000:8000"
    depends_on:
      - "fuseki"
    environment:
      - SPARQL_ENDPOINT_QUERY=http://blazegraph:8080/blazegraph/sparql
      - SPARQL_ENDPOINT_UPDATE=http://blazegraph:8080/blazegraph/sparql
      - LOG_LEVEL=DEBUG
  blazegraph:
    image: "metaphacts/blazegraph-basic"
